title: Wuhu Island Government
description: >-
  The Wuhu Island Government Portal is where you can read about the Wuhu Island,
  and access government services
baseurl: ""
url: "https://wuhugov.neocities.org"

plugins:
  - jekyll-seo-tag
  - jekyll-figure
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
